/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panel;

import Controller.Provider.Control_transaksiList;
import View.Dialog.Transaksi.inputTransaksi;
import View.Dialog.Transaksi.updateTransaksi;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author MohamadEsa
 */
public class transaksiPanel extends javax.swing.JPanel {

  /**
   * Creates new form userPanel
   */
  
  Control_transaksiList c;
  public updateTransaksi ubah = null;
  public detailtransaksiPanel detail = null;
  
  public transaksiPanel() {
    initComponents();
    c = new Control_transaksiList(this);
    refresh();
    detail = new detailtransaksiPanel(this);
    panelDetail.add(detail, "detail");
    CardLayout cl = (CardLayout) panelDetail.getLayout();
    cl.show(panelDetail, "detail");
  }

  public JTable getTabelDataTransaksi() {
    return tabelDataTransaksi;
  }

  public JTextField getTxtCari() {
    return txtCari;
  }  
  
  public void refresh(){
    c.isiTable();
    
    btnAdd.setEnabled(true);
    btnEdit.setEnabled(false);
    btnDelete.setEnabled(false);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel5 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    btnAdd = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    txtCari = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();
    jSplitPane1 = new javax.swing.JSplitPane();
    panelDetail = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabelDataTransaksi = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

    jPanel5.setBackground(new java.awt.Color(99, 170, 227));

    jPanel3.setBackground(new java.awt.Color(181, 215, 242));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

    btnAdd.setBackground(new java.awt.Color(0, 123, 255));
    btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add.png"))); // NOI18N
    btnAdd.setPreferredSize(new java.awt.Dimension(75, 25));
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });
    jPanel1.add(btnAdd);

    btnEdit.setBackground(new java.awt.Color(255, 193, 7));
    btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/edit.png"))); // NOI18N
    btnEdit.setPreferredSize(new java.awt.Dimension(75, 25));
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel1.add(btnEdit);

    btnDelete.setBackground(new java.awt.Color(220, 53, 69));
    btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/delete.png"))); // NOI18N
    btnDelete.setPreferredSize(new java.awt.Dimension(75, 25));
    btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnDeleteMouseClicked(evt);
      }
    });
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanel1.add(btnDelete);

    txtCari.setPreferredSize(new java.awt.Dimension(6, 25));

    jButton4.setBackground(new java.awt.Color(0, 0, 0));
    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/search.png"))); // NOI18N
    jButton4.setPreferredSize(new java.awt.Dimension(75, 25));
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jSplitPane1.setBorder(null);
    jSplitPane1.setDividerLocation(543);
    jSplitPane1.setDividerSize(3);

    panelDetail.setLayout(new java.awt.CardLayout());
    jSplitPane1.setRightComponent(panelDetail);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 402));
    jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jScrollPane1MouseClicked(evt);
      }
    });

    tabelDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tabelDataTransaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    tabelDataTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelDataTransaksiMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tabelDataTransaksi);

    jSplitPane1.setLeftComponent(jScrollPane1);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setText("KELOLA TRANSAKSI");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(724, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    add(jPanel5);
  }// </editor-fold>//GEN-END:initComponents

  private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_btnDeleteMouseClicked

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     if(tabelDataTransaksi.getSelectedRow()>=0){
            int dialog = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?","Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if(dialog == JOptionPane.YES_OPTION){
                String id = tabelDataTransaksi.getValueAt(tabelDataTransaksi.getSelectedRow(), 0).toString();
                c.delete(id);
                refresh();
            }
        } else{
            JOptionPane.showMessageDialog(this, "Pilih Data yang akan Dihapus","Peringatan",JOptionPane.WARNING_MESSAGE);
        }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
   
  }//GEN-LAST:event_jScrollPane1MouseClicked

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    new inputTransaksi(this).setVisible(true);
    refresh();
  }//GEN-LAST:event_btnAddActionPerformed

  private void tabelDataTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataTransaksiMouseClicked
    int tableData = tabelDataTransaksi.getSelectedRow();
    ubah = new updateTransaksi(this);
    
    
    ubah.id =tabelDataTransaksi.getValueAt(tableData, 0).toString();
    ubah.kategori =tabelDataTransaksi.getValueAt(tableData, 1).toString();
    ubah.provider =tabelDataTransaksi.getValueAt(tableData, 2).toString();
    ubah.produk =tabelDataTransaksi.getValueAt(tableData, 3).toString();
    ubah.keterangan =tabelDataTransaksi.getValueAt(tableData, 4).toString();
    ubah.no_pel =tabelDataTransaksi.getValueAt(tableData, 5).toString();
    ubah.harga =tabelDataTransaksi.getValueAt(tableData, 6).toString();
    ubah.wkt_pesan =tabelDataTransaksi.getValueAt(tableData, 7).toString();
    ubah.status =tabelDataTransaksi.getValueAt(tableData, 8).toString();
    ubah.pembayaran =tabelDataTransaksi.getValueAt(tableData, 9).toString();
    ubah.tgl_bayar =tabelDataTransaksi.getValueAt(tableData, 10).toString();
    ubah.sn_id =tabelDataTransaksi.getValueAt(tableData, 11).toString();
    ubah.dipilih();
    
    
    detail.id =tabelDataTransaksi.getValueAt(tableData, 0).toString();
    detail.kategori =tabelDataTransaksi.getValueAt(tableData, 1).toString();
    detail.provider =tabelDataTransaksi.getValueAt(tableData, 2).toString();
    detail.produk =tabelDataTransaksi.getValueAt(tableData, 3).toString();
    detail.keterangan =tabelDataTransaksi.getValueAt(tableData, 4).toString();
    detail.no_pel =tabelDataTransaksi.getValueAt(tableData, 5).toString();
    detail.harga =tabelDataTransaksi.getValueAt(tableData, 6).toString();
    detail.wkt_pesan =tabelDataTransaksi.getValueAt(tableData, 7).toString();
    detail.status =tabelDataTransaksi.getValueAt(tableData, 8).toString();
    detail.pembayaran =tabelDataTransaksi.getValueAt(tableData, 9).toString();
    detail.tgl_bayar =tabelDataTransaksi.getValueAt(tableData, 10).toString();
    detail.sn_id =tabelDataTransaksi.getValueAt(tableData, 11).toString();
    detail.dipilih();

    CardLayout cl = (CardLayout) panelDetail.getLayout();
    cl.show(panelDetail, "detail");
    
    btnAdd.setEnabled(false);
    btnDelete.setEnabled(true);
    btnEdit.setEnabled(true);
  }//GEN-LAST:event_tabelDataTransaksiMouseClicked

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    if(tabelDataTransaksi.getSelectedRow()>=0){
      ubah.setVisible(true);
      refresh();
    } else{
      JOptionPane.showMessageDialog(this, "Pilih Data yang akan Diubah","Peringatan",JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btnEditActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(txtCari.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Pencarian Belum Ditentukan","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else{
      c.search(this);
    }
  }//GEN-LAST:event_jButton4ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JPanel panelDetail;
  private javax.swing.JTable tabelDataTransaksi;
  private javax.swing.JTextField txtCari;
  // End of variables declaration//GEN-END:variables
}
