/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Form;

import Model.User;
import View.Dialog.Login.Login;
import View.Dialog.muatGambar;
import View.Panel.berandaPanel;
import View.Panel.kategoriPanel;
import View.Panel.produkPanel;
import View.Panel.providerPanel;
import View.Panel.transaksiPanel;
import View.Panel.userPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MohamadEsa
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
  
    private final berandaPanel panel2 = new berandaPanel();
    private final transaksiPanel panel3 = new transaksiPanel();
    
    private final userPanel panel1 = new userPanel();
    private final kategoriPanel panel4 = new kategoriPanel();
    private final produkPanel panel5 = new produkPanel();
    private final providerPanel panel6 = new providerPanel();
    String namaproject = "Pengelolaan Transaksi Pulsa";
    String versi = "Alpha";
    String file = "/Assets/Logo.png";
    String unem = User.getNama();
    public Dashboard() {
        initComponents();
        this.setTitle(namaproject+" - "+versi);
        this.setExtendedState(MAXIMIZED_BOTH);
        panelBody.add(panel1, "user");
        panelBody.add(panel2, "beranda");
        panelBody.add(panel3, "transaksi");
        panelBody.add(panel4, "kategori");
        panelBody.add(panel5, "produk");
        panelBody.add(panel6, "provider");
        System.out.println(unem);
        txtUsername.setText(unem);
        CardLayout cl = (CardLayout) panelBody.getLayout();
        cl.show(panelBody, "beranda");
    }


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel4 = new muatGambar(file);
    txtUsername = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    menus = new javax.swing.JPanel();
    btnBeranda = new javax.swing.JPanel();
    labelBeranda = new javax.swing.JLabel();
    btnMaster = new javax.swing.JPanel();
    labelMaster = new javax.swing.JLabel();
    btnTransaksi = new javax.swing.JPanel();
    labelTransaksi = new javax.swing.JLabel();
    btnLaporan = new javax.swing.JPanel();
    labelLaporan = new javax.swing.JLabel();
    btnLaporan1 = new javax.swing.JPanel();
    labelLaporan1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    panelBody = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setState(56);

    jPanel1.setBackground(new java.awt.Color(178, 190, 200));

    jPanel3.setBackground(new java.awt.Color(229, 241, 251));
    jPanel3.setPreferredSize(new java.awt.Dimension(150, 473));

    jPanel4.setBackground(new java.awt.Color(205, 205, 205));

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 130, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 110, Short.MAX_VALUE)
    );

    txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtUsername.setText("USERNAME");
    txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtUsername)
        .addContainerGap())
    );

    jScrollPane2.setBorder(null);

    menus.setBackground(new java.awt.Color(0, 0, 0));
    menus.setLayout(new java.awt.GridLayout(5, 0, 0, 2));

    btnBeranda.setBackground(new java.awt.Color(229, 241, 251));
    btnBeranda.setPreferredSize(new java.awt.Dimension(164, 15));

    labelBeranda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
    labelBeranda.setText("BERANDA");
    labelBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    labelBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelBerandaMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        labelBerandaMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        labelBerandaMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnBerandaLayout = new javax.swing.GroupLayout(btnBeranda);
    btnBeranda.setLayout(btnBerandaLayout);
    btnBerandaLayout.setHorizontalGroup(
      btnBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnBerandaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnBerandaLayout.setVerticalGroup(
      btnBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnBerandaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menus.add(btnBeranda);

    btnMaster.setBackground(new java.awt.Color(229, 241, 251));
    btnMaster.setPreferredSize(new java.awt.Dimension(164, 15));

    labelMaster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/masterdata.png"))); // NOI18N
    labelMaster.setText("MASTER DATA");
    labelMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    labelMaster.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelMasterMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        labelMasterMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        labelMasterMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnMasterLayout = new javax.swing.GroupLayout(btnMaster);
    btnMaster.setLayout(btnMasterLayout);
    btnMasterLayout.setHorizontalGroup(
      btnMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnMasterLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnMasterLayout.setVerticalGroup(
      btnMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnMasterLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menus.add(btnMaster);

    btnTransaksi.setBackground(new java.awt.Color(229, 241, 251));
    btnTransaksi.setPreferredSize(new java.awt.Dimension(164, 15));

    labelTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/transaction.png"))); // NOI18N
    labelTransaksi.setText("TRANSAKSI");
    labelTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    labelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelTransaksiMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        labelTransaksiMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        labelTransaksiMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnTransaksiLayout = new javax.swing.GroupLayout(btnTransaksi);
    btnTransaksi.setLayout(btnTransaksiLayout);
    btnTransaksiLayout.setHorizontalGroup(
      btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnTransaksiLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnTransaksiLayout.setVerticalGroup(
      btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnTransaksiLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menus.add(btnTransaksi);

    btnLaporan.setBackground(new java.awt.Color(229, 241, 251));
    btnLaporan.setPreferredSize(new java.awt.Dimension(164, 15));

    labelLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/report.png"))); // NOI18N
    labelLaporan.setText("LAPORAN");
    labelLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    labelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelLaporanMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        labelLaporanMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        labelLaporanMouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnLaporanLayout = new javax.swing.GroupLayout(btnLaporan);
    btnLaporan.setLayout(btnLaporanLayout);
    btnLaporanLayout.setHorizontalGroup(
      btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnLaporanLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnLaporanLayout.setVerticalGroup(
      btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnLaporanLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menus.add(btnLaporan);

    btnLaporan1.setBackground(new java.awt.Color(229, 241, 251));
    btnLaporan1.setPreferredSize(new java.awt.Dimension(164, 15));

    labelLaporan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    labelLaporan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
    labelLaporan1.setText("LOGOUT");
    labelLaporan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    labelLaporan1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        labelLaporan1MouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        labelLaporan1MouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        labelLaporan1MouseExited(evt);
      }
    });

    javax.swing.GroupLayout btnLaporan1Layout = new javax.swing.GroupLayout(btnLaporan1);
    btnLaporan1.setLayout(btnLaporan1Layout);
    btnLaporan1Layout.setHorizontalGroup(
      btnLaporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnLaporan1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelLaporan1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        .addContainerGap())
    );
    btnLaporan1Layout.setVerticalGroup(
      btnLaporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(btnLaporan1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelLaporan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    menus.add(btnLaporan1);

    jScrollPane2.setViewportView(menus);

    panelBody.setLayout(new java.awt.CardLayout());

    jPanel6.setBackground(new java.awt.Color(99, 170, 227));

    jPanel7.setBackground(new java.awt.Color(229, 241, 251));
    jPanel7.setLayout(null);

    jPanel8.setBackground(new java.awt.Color(229, 241, 251));

    jPanel5.setOpaque(false);
    jPanel5.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

    jButton1.setBackground(new java.awt.Color(255, 193, 7));
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
    jButton1.setText("PENGGUNA");
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton1);

    jButton2.setBackground(new java.awt.Color(39, 162, 67));
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/kategori.png"))); // NOI18N
    jButton2.setText("KATEGORI");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton2);

    jButton3.setBackground(new java.awt.Color(255, 193, 7));
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/provider.png"))); // NOI18N
    jButton3.setText("PROVIDER");
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton3);

    jButton4.setBackground(new java.awt.Color(39, 162, 67));
    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/product.png"))); // NOI18N
    jButton4.setText("PRODUK");
    jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton4.setPreferredSize(new java.awt.Dimension(150, 150));
    jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    jPanel5.add(jButton4);

    jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("MENU MASTER");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel8Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(48, Short.MAX_VALUE))
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(97, Short.MAX_VALUE))
    );

    jPanel7.add(jPanel8);
    jPanel8.setBounds(10, 10, 650, 420);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    panelBody.add(jPanel6, "card3");

    jScrollPane1.setViewportView(panelBody);

    jPanel2.setBackground(new java.awt.Color(229, 241, 251));

    jLabel3.setText("yyyy-MMMMM-dd || 00:00 WIB");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
          .addComponent(jScrollPane2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void labelBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBerandaMouseClicked
    btnBeranda.setBackground(new Color(178, 190, 200));
    CardLayout cl = (CardLayout) panelBody.getLayout();
    cl.show(panelBody, "beranda");
  }//GEN-LAST:event_labelBerandaMouseClicked

  private void labelBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBerandaMouseExited
    btnBeranda.setBackground(new Color(229, 241, 251));
    
  }//GEN-LAST:event_labelBerandaMouseExited

  private void labelBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBerandaMouseEntered
    btnBeranda.setBackground(new Color(204, 216, 226));
  }//GEN-LAST:event_labelBerandaMouseEntered

  private void labelMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasterMouseClicked
    btnMaster.setBackground(new Color(178, 190, 200));
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "card3");
  }//GEN-LAST:event_labelMasterMouseClicked

  private void labelMasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasterMouseEntered
    btnMaster.setBackground(new Color(204, 216, 226));
  }//GEN-LAST:event_labelMasterMouseEntered

  private void labelMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMasterMouseExited
    btnMaster.setBackground(new Color(229, 241, 251));
  }//GEN-LAST:event_labelMasterMouseExited

  private void labelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksiMouseClicked
    btnTransaksi.setBackground(new Color(178, 190, 200));
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "transaksi");
  }//GEN-LAST:event_labelTransaksiMouseClicked

  private void labelTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksiMouseEntered
    btnTransaksi.setBackground(new Color(204, 216, 226));
  }//GEN-LAST:event_labelTransaksiMouseEntered

  private void labelTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksiMouseExited
    btnTransaksi.setBackground(new Color(229, 241, 251));
  }//GEN-LAST:event_labelTransaksiMouseExited

  private void labelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporanMouseClicked
    btnLaporan.setBackground(new Color(178, 190, 200));
  }//GEN-LAST:event_labelLaporanMouseClicked

  private void labelLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporanMouseEntered
    btnLaporan.setBackground(new Color(204, 216, 226));
  }//GEN-LAST:event_labelLaporanMouseEntered

  private void labelLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporanMouseExited
    btnLaporan.setBackground(new Color(229, 241, 251));
  }//GEN-LAST:event_labelLaporanMouseExited

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "user");
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "kategori");
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "provider");
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    CardLayout c2 = (CardLayout) panelBody.getLayout();
    c2.show(panelBody, "produk");
  }//GEN-LAST:event_jButton4ActionPerformed

  private void labelLaporan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporan1MouseClicked
    btnLaporan1.setBackground(new Color(178, 190, 200));
    int ok = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar Akun?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok==0){
          User.setId("");
          User.setNama("");
          User.setPassword("");
          User.setUsername("");
            new Login().show();
            this.dispose();
        }
  }//GEN-LAST:event_labelLaporan1MouseClicked

  private void labelLaporan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporan1MouseEntered
    btnLaporan1.setBackground(new Color(204, 216, 226));
  }//GEN-LAST:event_labelLaporan1MouseEntered

  private void labelLaporan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporan1MouseExited
    btnLaporan1.setBackground(new Color(229, 241, 251));
  }//GEN-LAST:event_labelLaporan1MouseExited

   

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel btnBeranda;
  private javax.swing.JPanel btnLaporan;
  private javax.swing.JPanel btnLaporan1;
  private javax.swing.JPanel btnMaster;
  private javax.swing.JPanel btnTransaksi;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel labelBeranda;
  private javax.swing.JLabel labelLaporan;
  private javax.swing.JLabel labelLaporan1;
  private javax.swing.JLabel labelMaster;
  private javax.swing.JLabel labelTransaksi;
  private javax.swing.JPanel menus;
  private javax.swing.JPanel panelBody;
  private javax.swing.JLabel txtUsername;
  // End of variables declaration//GEN-END:variables
}
