/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Dialog.Transaksi;

import Config.Config;
import Controller.Transaksi.Control_transaksiUpdate;
import View.Panel.transaksiPanel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author MohamadEsa
 */
public class updateTransaksi extends javax.swing.JDialog implements Config{

  /**
   * Creates new form MenuMaster
   */
  public String id, kategori, provider, produk, keterangan, no_pel, harga, wkt_pesan, status, pembayaran, tgl_bayar, sn_id;
  transaksiPanel view;
  Control_transaksiUpdate c;
  
  public updateTransaksi(transaksiPanel view) {
    initComponents();
    this.setTitle(updateTransaksi);
//    this.setAlwaysOnTop(true);
    c = new Control_transaksiUpdate(this);
    txtID.setVisible(false);
    this.view=view;
    this.setLocationRelativeTo(view);
  }

  public JComboBox<String> getCbPembayaran() {
    return cbPembayaran;
  }

  public JComboBox<String> getCbStatus() {
    return cbStatus;
  }

  public JTextField getTxtHarga() {
    return txtHarga;
  }

  public JLabel getTxtID() {
    return txtID;
  }

  public JTextField getTxtKategori() {
    return txtKategori;
  }

  public JTextArea getTxtKeterangan() {
    return txtKeterangan;
  }

  public JTextField getTxtNo_pel() {
    return txtNo_pel;
  }

  public JTextField getTxtProduk() {
    return txtProduk;
  }

  public JTextField getTxtProvider() {
    return txtProvider;
  }

  public JTextField getTxtSN_id() {
    return txtSN_id;
  }

  public JTextField getTxtTgl_bayar() {
    return txtTgl_bayar;
  }

  public JTextField getTxtWaktu() {
    return txtWaktu;
  }
  
   public void waktu_pesan(){
        Date tgl = new Date();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        txtWaktu.setText(df.format(tgl));
    }
   
   public void tanggal_bayar(){
        Date tgl = new Date();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        txtTgl_bayar.setText(df.format(tgl));
    }
  
  public void dipilih(){
      view.ubah = this;
      txtID.setText(id);
      txtKategori.setText(kategori);
      txtProvider.setText(provider);
      txtProduk.setText(produk);
      txtKeterangan.setText(keterangan);
      txtNo_pel.setText(no_pel);
      txtHarga.setText(harga);
      txtWaktu.setText(wkt_pesan);
      cbStatus.setSelectedItem(status);
      cbPembayaran.setSelectedItem(pembayaran);
      txtTgl_bayar.setText(tgl_bayar);
      txtSN_id.setText(sn_id);
  }
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    txtID = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtKeterangan = new javax.swing.JTextArea();
    jLabel4 = new javax.swing.JLabel();
    txtHarga = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    txtKategori = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtProduk = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtNo_pel = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    cbPembayaran = new javax.swing.JComboBox<>();
    jLabel9 = new javax.swing.JLabel();
    cbStatus = new javax.swing.JComboBox<>();
    jLabel10 = new javax.swing.JLabel();
    txtWaktu = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    txtTgl_bayar = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    txtSN_id = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    txtProvider = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(99, 170, 227));

    jPanel2.setBackground(new java.awt.Color(229, 241, 251));

    txtID.setText("ID");

    jButton1.setText("PROSES");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel3.setText("Keterangan");

    txtKeterangan.setColumns(20);
    txtKeterangan.setRows(5);
    jScrollPane1.setViewportView(txtKeterangan);

    jLabel4.setText("Harga");

    jLabel5.setText("Kategori");

    jLabel6.setText("Produk");

    jLabel7.setText("No. Tlp/ID");

    jLabel8.setText("Pembayaran");

    cbPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unknown", "Non-Tunai", "Tunai" }));
    cbPembayaran.setEnabled(false);

    jLabel9.setText("Status Transaksi");

    cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Belum Membayar", "Telah Membayar" }));
    cbStatus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbStatusActionPerformed(evt);
      }
    });

    jLabel10.setText("Waktu Pesan");

    jLabel11.setText("Tanggal Bayar");

    txtTgl_bayar.setEnabled(false);

    jLabel12.setText("Kode SN/ID Voucher");

    jLabel13.setText("Provider");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel12)
            .addGap(25, 25, 25)
            .addComponent(txtSN_id))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtID)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5)
              .addComponent(jLabel7)
              .addComponent(jLabel8)
              .addComponent(jLabel9)
              .addComponent(jLabel10)
              .addComponent(jLabel11)
              .addComponent(jLabel6)
              .addComponent(jLabel13))
            .addGap(43, 43, 43)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtTgl_bayar)
              .addComponent(txtWaktu)
              .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtNo_pel)
              .addComponent(txtHarga)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
              .addComponent(cbPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtKategori)
              .addComponent(txtProvider)
              .addComponent(txtProduk))))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtID)
        .addGap(9, 9, 9)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNo_pel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cbPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTgl_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtSN_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    c.update(this);
    view.refresh();
    this.dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
    if(cbStatus.getSelectedItem().equals("Telah Membayar")){
      tanggal_bayar();
      cbPembayaran.setEnabled(true);
      txtTgl_bayar.setEnabled(true);
    } else {
      cbPembayaran.setEnabled(false);
      txtTgl_bayar.setEnabled(false);
      cbPembayaran.setSelectedItem("Pilih");
      txtTgl_bayar.setText("");
    }
  }//GEN-LAST:event_cbStatusActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> cbPembayaran;
  private javax.swing.JComboBox<String> cbStatus;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField txtHarga;
  private javax.swing.JLabel txtID;
  private javax.swing.JTextField txtKategori;
  private javax.swing.JTextArea txtKeterangan;
  private javax.swing.JTextField txtNo_pel;
  private javax.swing.JTextField txtProduk;
  private javax.swing.JTextField txtProvider;
  private javax.swing.JTextField txtSN_id;
  private javax.swing.JTextField txtTgl_bayar;
  private javax.swing.JTextField txtWaktu;
  // End of variables declaration//GEN-END:variables
}
